main:
	g++ -g connectPeer.cpp handleClient.cpp informTracker.cpp peer.cpp processCommands.cpp SHA.cpp startClient.cpp startServer.cpp threadPool.cpp utility.cpp -lssl -lcrypto -Wdeprecated-declarations -Wformat-extra-args
