main:
	g++ -g peer.cpp startClient.cpp utility.cpp startServer.cpp handleClient.cpp processCommands.cpp SHA.cpp connectPeer.cpp threadPool.cpp -lssl -lcrypto -Wdeprecated-declarations -Wformat-extra-args
